use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // Linker args for the firmware binaries. We use the un-suffixed
    // `rustc-link-arg` (rather than `-bins`) so it applies to the crate's
    // `examples/` too — they are the flashable targets in this SDK (the crate
    // itself is a library).

    // --nmagic avoids excessive section alignment/padding on the small L0 flash.
    println!("cargo:rustc-link-arg=--nmagic");

    // link.x comes from cortex-m-rt; it pulls in memory.x generated by
    // embassy-stm32 (the `memory-x` feature) for the STM32L083CZ memory map.
    println!("cargo:rustc-link-arg=-Tlink.x");

    // FOTA: when the `fota-active` feature is set, link into the ACTIVE slot
    // (0x0800_B800) instead of at 0x0800_0000, so the binary boots under the
    // crates/bootloader loader (docs/fota.md). We copy our own memory.x onto
    // the linker search path; because this build script belongs to the crate being
    // built (its examples), its search path is consulted before embassy-stm32's, so
    // `link.x`'s `INCLUDE memory.x` resolves to OURS (FLASH = ACTIVE) — the canonical
    // embassy app-vs-bootloader pattern (cf. embassy examples/boot/application/stm32l0,
    // which likewise keeps `memory-x` on and ships its own memory.x). Without the
    // feature, nothing changes and embassy-stm32's full-chip memory.x is used.
    if env::var_os("CARGO_FEATURE_FOTA_ACTIVE").is_some() {
        let out = PathBuf::from(env::var_os("OUT_DIR").unwrap());
        fs::write(out.join("memory.x"), include_bytes!("link/memory-fota-app.x")).unwrap();
        println!("cargo:rustc-link-search={}", out.display());
        println!("cargo:rerun-if-changed=link/memory-fota-app.x");
    }
}
