fn main() {
    // Linker args for the firmware binaries. We use the un-suffixed
    // `rustc-link-arg` (rather than `-bins`) so it applies to the crate's
    // `examples/` too — they are the flashable targets in this SDK (the crate
    // itself is a library).

    // --nmagic avoids excessive section alignment/padding on the small L0 flash.
    println!("cargo:rustc-link-arg=--nmagic");

    // link.x comes from cortex-m-rt; it pulls in memory.x generated by
    // embassy-stm32 (the `memory-x` feature) for the STM32L083CZ memory map.
    println!("cargo:rustc-link-arg=-Tlink.x");
}
