//! fota-sign — sign a firmware image into a signed FOTA manifest (docs/fota.md).
//!
//!   just fota-sign pubkey
//!       Print the vendor public key as a Rust array to paste into the firmware
//!       (`tower::fota::VENDOR_PUBKEY`).
//!
//!   just fota-sign sign --version <N> --in <image.bin> --out <image.fmanifest> [--hw-id <H>]
//!       Hash the image (SHA-256), build a Manifest {version, size, sha256, hw_id}, sign
//!       its canonical bytes with the vendor Ed25519 key, and write the 116-byte signed
//!       manifest blob. Deliver it alongside the image; the device verifies it (signature
//!       + image hash + rollback) before arming a swap.
//!
//! The key here is a fixed **DEV** seed for bring-up — anyone can read it, so images it
//! signs are NOT production-trustworthy. For production, replace `DEV_SEED` with a key
//! read from a file / HSM and keep the private half secret.

use std::process::exit;

use ed25519_dalek::{Signer, SigningKey};
use sha2::{Digest, Sha256};
use tower_protocol::fota::Manifest;

/// DEV signing seed (32 bytes) — bring-up only; see the module note. The matching public
/// key (`fota-sign pubkey`) is baked into the firmware.
const DEV_SEED: [u8; 32] = *b"tower-fota dev signing key v1!!!";

fn signing_key() -> SigningKey {
    SigningKey::from_bytes(&DEV_SEED)
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    match args.get(1).map(String::as_str) {
        Some("pubkey") => cmd_pubkey(),
        Some("sign") => cmd_sign(&args[2..]),
        _ => {
            eprintln!(
                "usage:\n  fota-sign pubkey\n  fota-sign sign --version <N> --in <image.bin> --out <out.fmanifest> [--hw-id <H>]"
            );
            exit(2);
        }
    }
}

fn cmd_pubkey() {
    let pk = signing_key().verifying_key().to_bytes();
    println!("// FOTA vendor public key (DEV) — generated by `fota-sign pubkey`.");
    print!("pub const VENDOR_PUBKEY: [u8; 32] = [");
    for (i, b) in pk.iter().enumerate() {
        if i % 8 == 0 {
            print!("\n   ");
        }
        print!(" 0x{b:02x},");
    }
    println!("\n];");
}

fn cmd_sign(args: &[String]) {
    let mut version: Option<u32> = None;
    let mut hw_id: u32 = 0;
    let mut in_path: Option<String> = None;
    let mut out_path: Option<String> = None;

    let mut i = 0;
    while i < args.len() {
        let val = || args.get(i + 1).cloned().unwrap_or_else(|| die("missing value"));
        match args[i].as_str() {
            "--version" => version = Some(val().parse().unwrap_or_else(|_| die("bad --version"))),
            "--hw-id" => hw_id = val().parse().unwrap_or_else(|_| die("bad --hw-id")),
            "--in" => in_path = Some(val()),
            "--out" => out_path = Some(val()),
            other => die(&format!("unknown arg: {other}")),
        }
        i += 2;
    }

    let version = version.unwrap_or_else(|| die("--version is required"));
    let in_path = in_path.unwrap_or_else(|| die("--in is required"));
    let out_path = out_path.unwrap_or_else(|| die("--out is required"));

    let image = std::fs::read(&in_path).unwrap_or_else(|e| die(&format!("read {in_path}: {e}")));
    let mut hasher = Sha256::new();
    hasher.update(&image);
    let sha256: [u8; 32] = hasher.finalize().into();

    let manifest = Manifest {
        flags: 0,
        hw_id,
        version,
        size: image.len() as u32,
        sha256,
    };
    let sig = signing_key().sign(&manifest.encode());
    let signed = manifest.encode_signed(&sig.to_bytes());
    std::fs::write(&out_path, signed).unwrap_or_else(|e| die(&format!("write {out_path}: {e}")));

    eprintln!(
        "signed v{} hw_id={} ({} B image, sha256 {:02x}{:02x}{:02x}{:02x}..) -> {} ({} B)",
        version,
        hw_id,
        image.len(),
        sha256[0],
        sha256[1],
        sha256[2],
        sha256[3],
        out_path,
        signed.len(),
    );
}

fn die(msg: &str) -> ! {
    eprintln!("error: {msg}");
    exit(1);
}

#[cfg(test)]
mod tests {
    use super::*;
    use tower_protocol::fota::{VENDOR_PUBKEY, verify_signed};

    /// The public key derived from this tool's `DEV_SEED` MUST equal the `VENDOR_PUBKEY`
    /// baked into the bootloader (the trust anchor it verifies against). The seed lives here
    /// and the baked key lives in `tower-protocol`, so they *can* drift — and if they do,
    /// every image this tool signs would be silently rejected by the bootloader. Pinning them
    /// together makes that drift a failed test, not a field-only mystery. (Regenerate the
    /// baked key with `fota-sign pubkey` whenever the seed changes.)
    #[test]
    fn dev_seed_matches_baked_vendor_pubkey() {
        assert_eq!(
            signing_key().verifying_key().to_bytes(),
            VENDOR_PUBKEY,
            "DEV_SEED-derived pubkey != tower_protocol::fota::VENDOR_PUBKEY — \
             run `fota-sign pubkey` and update the baked key"
        );
    }

    /// The whole point of the signing path: a manifest signed on the host with `ed25519-dalek`
    /// verifies on the device with `salty` (`tower_protocol::verify_signed`). Both follow
    /// RFC 8032, so the same seed yields the same key and interoperable signatures.
    #[test]
    fn dalek_signed_verifies_with_salty() {
        let key = signing_key();
        let pubkey = key.verifying_key().to_bytes();

        let image = b"a pretend firmware image of some length";
        let mut h = Sha256::new();
        h.update(image);
        let sha256: [u8; 32] = h.finalize().into();
        let m = Manifest {
            flags: 0,
            hw_id: 0,
            version: 7,
            size: image.len() as u32,
            sha256,
        };

        let sig = key.sign(&m.encode());
        let signed = m.encode_signed(&sig.to_bytes());

        // Device-side salty verification accepts the host's dalek signature.
        assert_eq!(verify_signed(&pubkey, &signed), Some(m));

        // And rejects a tampered image hash (flip a byte of the sha in the manifest body).
        let mut bad = signed;
        bad[20] ^= 0x01;
        assert!(verify_signed(&pubkey, &bad).is_none());
    }
}
